server:
  port: 8082
spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuanchangxin/363Tec.git
          basedir: D:\idea_workspace\363Tec\363Tec\somnous-parent\config-center
          search-paths: '{application}'
          force-pull: true
          clone-on-start: true
          username: yuanchangxin
          password: YCXlqh3172678